name: Mastermind Century Group
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07526882
title: Blog
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ce00'
    - '#000000'
    - '#003600'
    - '#007e00'
    - '#005c00'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
