name: Mastermind Century Group
favicon: null
layout_spectrum: 0.8377454930450767
typography_spectrum: 0.020038899965584278
title: Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3293122434988618
  lightness: 0.3031487560365349
  saturation: 0.48530563013628125
  rhythmicContrast: 0.7983267216477543
purpose: []
